### PR TITLE
move away from deprecated apiVersion for CRD

### LINKED ISSUE #53: Update CRD apiVersion to v1
v1beta1 is deprecated as of Kubernetes 1.19

### PR DESCRIPTION
**Pull request by tariq1890**
Fixes #53

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by tariq1890** [comment]
Can this be merged :)?

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
Thanks!

**Pull request merged**
