### PR TITLE
Add liveness check and endpoint to controller

### PR DESCRIPTION
**Pull request by demonCoder95**
This patch adds a liveness probe endpoint to the controller by checking time elapsed since last `refresh` was successful. If it's been `5*interval` duration since the last refresh, probe fails.

Reference: `stackset-controller` liveness probe endpoint code [here](https://github.com/zalando-incubator/stackset-controller/blob/d9435669e6a54b126b43ce244eb3b1fa10506471/controller/stackset.go#L133).
Issue: This patch addresses [this](https://github.bus.zalan.do/teapot/issues/issues/3294) issue which is part of a Post Mortem action item [here](https://docs.google.com/document/d/1GX9shnO61pZuIYWEboRMIML9bGbXRulegpJOzqJxofg/edit#).

### CODE REVIEW

**Comment by rodrigodelmonte** [comment]
Thanks for the improvement!

How trick would be to add a test for it? Anyway it is possible to test in a dev environment.

Can you also update the examples [0] and [1] ?
[0] - https://github.com/zalando-incubator/kube-aws-iam-controller/blob/master/docs/deployment.yaml 
[1] - https://github.com/zalando-incubator/kube-aws-iam-controller/blob/master/docs/deployment_with_role.yaml

**Comment by demonCoder95** [comment]
Yes, I thought about adding a unit test but then I though it's simpler to check this in dev, like you suggested. I'll add a commit to patch the examples. Thanks :)

**Comment by rodrigodelmonte** [comment]
:+1:

**Comment by rodrigodelmonte** [comment]
:+1:

**Comment by demonCoder95** [comment]
👍

**Pull request merged**
